services:
  db:
    image: postgres
    env_file:
      - .env-vars
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env-vars
    depends_on:
      - db